### ISSUE TITLE
Conversion from STL does not produce the correct 3MF file

### ISSUE THREAD

**Issue by ansonl** [MosaicManufacturing/stl-to-3mf#4]
Hi,

I tried to run stl-to-3mf with a sample STL file and it produces a 3MF file with small model that is 2 dimensional and tilted.

```
stl-to-3mf DC-single-test.3mf ~/data/test.config DC-single "1,0,0,0|0,1,0,0|0,0,1,0|0,0,0,1" 1 1 1 DC-single.stl
```
[DC-single.zip](https://github.com/MosaicManufacturing/stl-to-3mf/files/12839411/DC-single.zip)

I put in an identity matrix as specified by the `util.Matrix4` file and my `test.config` file is empty. I'm just trying to convert the STL to 3MF without any transforms or printer settings. 

What is the proper usage of stl-to-3mf to produce the correct STL? @brandonbloch  Thank you. 

The original STL
![image](https://github.com/MosaicManufacturing/stl-to-3mf/assets/546458/11f5aeb7-9da2-4337-a553-2f07cd0755ed)

The produced 3MF
![image](https://github.com/MosaicManufacturing/stl-to-3mf/assets/546458/1c1abd27-78fd-493d-bc40-487aa037b54d)

**Comment by ansonl** [comment]
@brandonbloch  I tried updating the code to be compatible with the latest go3mf v0.24.2 on my fork https://github.com/ansonl/stl-to-3mf but got the same results of a unusable 3MF file from the sample STL above.

**Comment by brandonbloch** [comment]
Hi @ansonl,

This util is specifically useful for generating 3MF files that are ready-to-use with PrusaSlicer – to convert an STL to 3MF without any transforms or printer settings, I would recommend using [`go3mf`](https://github.com/HPInc/go3mf) directly (take a look at `stl.NewDecoder` and `go3mf.CreateWriter` in particular), rather than trying to make this util work.
